### ISSUE TITLE
sample hello-world configuration

### ISSUE THREAD

**Issue by gasperlf** [ibm-datapower/datapower-tutorials#6]
Im woking with docker container and with example: first configuration, but when import hello world and everything is good, after that type url: http://localhost:8000/api/pokemons/1 and show me this error 

{"stack":"ReferenceError: Integer is not defined\n    at Object.<anonymous> (store:///gatewayscript/example-error.js:10:9)\n    at Script.execute (gatewayscript:///datapower.js:147:24)\n    at Object.<anonymous> (gatewayscript:///datapower.js:499:55)","errorMessage":"Integer is not defined","errorCode":"0x8580005c","errorDescription":"GatewayScript console log message.","errorSuggestion":"GatewayScript console log message. Refer to the message for more information."}

**Comment by hstenzel** [comment]
@ozairs can you please take a look?

**Comment by ozairs** [comment]
I assume your testing the following lab: https://github.com/ibm-datapower/datapower-tutorials/blob/master/gatewayscript/gatewayscript-101.md

The backend service is located at `https://pokemons.mybluemix.net/api/pokemons/1`. Make sure your can hit it.

I suspect that the `localhost` hostname is not working on your machine. Can you run the command `docker ps` and paste the output here.

**Comment by aneeshananthakrishnan** [comment]
Hi,

I am also facing the same issue. @hstenzel - How did you resolve it?
C:\Users\AneeshAnand>docker ps
**CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS                                                                                                    NAMES
da1e152d23e2        ibmcom/datapower    "/bin/drouter"      5 days ago          Up 5 days           0.0.0.0:5554->5554/tcp, 0.0.0.0:8000-8010->8000-8010/tcp, 0.0.0.0:9090->9090/tcp, 0.0.0.0:9022->22/tcp   idg**

Thanks,
Aneesh.

**Comment by aneeshananthakrishnan** [comment]
When I checked the certificate validity, it looks like the the certificate is expired.
NotBefore | 2014-06-02T00:00:00Z
-- | --
NotAfter | 2017-06-06T12:00:00Z

How to obtain a valid certificate?

I see the following in the Datapower command prompt::
*************************************************************************************************************
20170902T173526.680Z [0x8120002f][ssl][error] ssl-client(ssl-client): tid(363568)[172.17.0.1] gtid(55620b2359aaebde00058c30): SSL library error: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
20170902T173526.680Z [0x80e006c1][mpgw][error] mpgw(rest-proxy): tid(363568)[172.17.0.1] gtid(55620b2359aaebde00058c30): Error in stream. Descriptor number unavailable. Additional information: Write error (8)
20170902T173526.680Z [0x80e00626][mpgw][error] mpgw(rest-proxy): tid(363568)[172.17.0.1] gtid(55620b2359aaebde00058c30): Error occurred when connecting to URL 'https://pokemons.mybluemix.net/favicon.ico'
20170902T173526.680Z [0x80e00126][mpgw][error] mpgw(rest-proxy): tid(363568)[172.17.0.1] gtid(55620b2359aaebde00058c30): Valid backside connection could not be established: Failed to establish a backside connection, url: https://pokemons.mybluemix.net/favicon.ico
20170902T173526.680Z [0x01130006][mpgw][error] mpgw(rest-proxy): tid(363568)[error][172.17.0.1] gtid(55620b2359aaebde00058c30): Failed to establish a backside connection
20170902T173526.683Z [0x81200026][ssl][error] ssl-client(ssl-client): tid(3295): SSL handshake certificate validation error with validation credentials ssl-client-valcred: certificate not trusted
20170902T173543.507Z [0x80e00161][mpgw][error] source-http(rest-proxy_rest-gw-fsh): tid(363584)[172.17.0.1]: Request processing failed: Connection terminated before request headers read because of the connection error occurs, from URL: 172.17.0.1:34478
20170902T173543.507Z [0x80e00161][mpgw][error] source-http(rest-proxy_rest-gw-fsh): tid(363552)[172.17.0.1]: Request processing failed: Connection terminated before request headers read because of the connection error occurs, from URL: 172.17.0.1:34474
*************************************************************************************************************

Thanks,
Aneesh.

**Comment by tonyffrench** [comment]
fixed https://github.com/ibm-datapower/datapower-tutorials/commit/42257a02d36fd0c24465d0bfb8f76bc326015b8a
